apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: edge-telemetry
  namespace: smart-retail
  labels:
    strimzi.io/cluster: retail-kafka
spec:
  partitions: 3
  replicas: 1
  config:
    retention.ms: 604800000  # 7 days
    segment.ms: 86400000      # 1 day
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: edge-images
  namespace: smart-retail
  labels:
    strimzi.io/cluster: retail-kafka
spec:
  partitions: 3
  replicas: 1
  config:
    retention.ms: 259200000   # 3 days
    segment.ms: 86400000

